module.exports = {
    OPERATION_FAILED: 0,
    SUCCESS: 1,
    UNAUTHORIZED: 2,
    CODE_NULL: 3,
    INACTIVE_CODE: 4,
    EMAIL_UNVERIFIED: 5,
    SEAT_UNAVAILABLE: 6,
    BOOKING_EXPIRED: 7,
    PAYMENT_FAILED: 8,
    SEND_EMAIL_FAILED: 11,
};
